"""

Problem

A string is simply an ordered collection of symbols selected from some alphabet and formed into a word; the length of a string is the number of symbols that it contains.

An example of a length 21 DNA string (whose alphabet contains the symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

Given: A DNA string s

of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s


Sample Dataset

AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC

Sample Output

20 12 17 21 

"""


with open('data/rosalind_dna.txt', 'r') as file:
    dna = file.read().rstrip()

#dna = 'TGGGGGTCCGACCAGTTACTTTAATCATTCAAGAATCGGCACGCGACAGAACGCGCGGTAGGCTGCGATCCAAATGTGCCGGCTCGGCGTCGGCGTAGGACTCTGAGGGAGAGTTCGTATTTTCAACGAAAACACGCGTATCTAGTAACCAGGGATACCATTTCCGCTTATCGCCGAGCGTTTCCGGCGACACCTGACCTGGCGTCGCAGTACGGCATCCGCCGTTCCACCGCCACGGCTAGTTCCAGTTATGTATACCTTCATATCAGAACCGTAGGTATCCAACTCACTTGCGGTCGTAAGCTACGCACCTCGCTAGTAGCTGTTCTCTCGCTGGTCCCCAAAAGGCCTGTTCGAGTTACACTGCTAGAACATTGAAATCATGTTGAGGGATCTGATCAGATGTCTTCGGGACCAATGTAGGTTCCGTAGTTCCTCCTTGTGCAGGAGCAATCTACGGATACTCGGAGCATCGGAGGCATATTAGTGTAAGGTTCGAGTTCGTGATTAAAGGTTTCGGTGTTTTCCCCTCCCTTGTTGTAGCATACAGAACCGACTGTTGCGCACAAGTATTTATGAGGCGGGGCGCACTTAATCCTCATCAATAAGCAGGATACTCTGTTCTCCGCATTAAGCTGGCACCTTGGCTACATACTTCTCGACAACAGAAGGCAATGCCATGTCGATCTACCGTACCAGAGCATACATACTGCCGTACGGTTTGGAGGGCGATTCCGCGCATGGGATCATGTCATCCTCAAATCAAGCTGCAGATCGAATCCTTCTGTGCCCAAAGAGGTCAGTTCCTTTTCTTTCCTGGTGTTCATCCCACTCGCCAGGAGCAGTTTTTCAGCATTAGTAGTGCATCATAATTTTAGTTCAACGCCTCGATCAGGACGTTCTTCAACCGCTGGACGGGCGGCCTCTCGG'
print(dna)

def count_nuc(string):
    count_dic = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for s in string:
        count_dic[s] +=1
    return count_dic


result=count_nuc(dna)

print(' '.join([str(val) for key, val in result.items()]))